project_id = "xtxwrvjdoexuymdkmzit"

[functions.generate-clothing-image]
verify_jwt = false

[functions.generate-model-avatar]
verify_jwt = false

[functions.virtual-tryon]
verify_jwt = false

[functions.generate-option-images]
verify_jwt = false

[functions.generate-suggestion-image]
verify_jwt = false

[functions.rate-outfit]
verify_jwt = false

[functions.analyze-body-profile]
verify_jwt = false

[functions.analyze-clothing]
verify_jwt = false

[functions.style-me]
verify_jwt = false
